const List<Map<String, String>> industries = [
  {'label': "Artificial Intelligence", 'value': "Artificial Intelligence"},
  {'label': "Machine Learning", 'value': "Machine Learning"},
  {'label': "Data Science", 'value': "Data Science"},
  {'label': "Software Development", 'value': "Software Development"},
  {'label': "Web Development", 'value': "Web Development"},
  {'label': "App Development", 'value': "App Development"},
  {'label': "Cybersecurity", 'value': "Cybersecurity"},
  {'label': "Cloud Computing", 'value': "Cloud Computing"},
  {'label': "DevOps", 'value': "DevOps"},
  {'label': "Database Management", 'value': "Database Management"},
  {'label': "Network Engineering", 'value': "Network Engineering"},
  {'label': "Hardware Engineering", 'value': "Hardware Engineering"},
  {'label': "UI/UX Design", 'value': "UI/UX Design"},
  {'label': "Digital Marketing", 'value': "Digital Marketing"},
  {'label': "Social Media Management", 'value': "Social Media Management"},
  {'label': "Brand Collaboration", 'value': "Brand Collaboration"},
  {'label': "Influencer Marketing Strategy", 'value': "Influencer Marketing Strategy"},
  {'label': "Email Marketing", 'value': "Email Marketing"},
  {'label': "Affiliate Marketing", 'value': "Affiliate Marketing"},
  {'label': "Project Management", 'value': "Project Management"},
  {'label': "Content Writing", 'value': "Content Writing"},
  {'label': "Video Production", 'value': "Video Production"},
  {'label': "Graphic Design", 'value': "Graphic Design"},
  {'label': "Audience Engagement", 'value': "Audience Engagement"},
  {'label': "Campaign Management", 'value': "Campaign Management"},
  {'label': "Performance Analysis", 'value': "Performance Analysis"},
  {'label': "SEO", 'value': "SEO"},
  {'label': "Business Analysis", 'value': "Business Analysis"},
  {'label': "Human Resources", 'value': "Human Resources"}
];
