// lib/constants/industries.dart
const List<Map<String, String>> industries = [
  {"value": "Retail and E-commerce", "label": "Retail and E-commerce"},
  {"value": "Transportation and logistics", "label": "Transportation and logistics"},
  {"value": "Hospitality and Travel", "label": "Hospitality and Travel"},
  {"value": "Food and Beverage", "label": "Food and Beverage"},
  {"value": "Professional Services", "label": "Professional Services"},
  {"value": "Consumer Services", "label": "Consumer Services"},
  {"value": "Healthcare and telemedicine", "label": "Healthcare and telemedicine"},
  {"value": "Fitness and Wellness", "label": "Fitness and Wellness"},
  {"value": "Manufacturing and Industrial", "label": "Manufacturing and Industrial"},
  {"value": "Technology and Software", "label": "Technology and Software"},
  {"value": "Banking and Financial Services", "label": "Banking and Financial Services"},
  {"value": "Education and E-learning", "label": "Education and E-learning"},
  {"value": "Construction and Engineering", "label": "Construction and Engineering"},
  {"value": "Automotive and Transportation", "label": "Automotive and Transportation"},
  {"value": "Entertainment and Media", "label": "Entertainment and Media"},
  {"value": "Non-profit and Charitable Organizations", "label": "Non-profit and Charitable Organizations"},
  {"value": "Energy and Utilities", "label": "Energy and Utilities"},
  {"value": "Government and Public Sector", "label": "Government and Public Sector"},
  {"value": "Beauty and Wellness", "label": "Beauty and Wellness"},
  {"value": "Fashion and Apparel", "label": "Fashion and Apparel"},
  {"value": "Home and Interior Design", "label": "Home and Interior Design"},
  {"value": "Agriculture and Farming", "label": "Agriculture and Farming"},
  {"value": "Sports and Recreation", "label": "Sports and Recreation"},
];
