const List<Map<String, String>> techExpertiseData = [
  {"value": "Artificial Intelligence", "label": "Artificial Intelligence"},
  {"value": "Blockchain Development", "label": "Blockchain Development"},
  {"value": "ChatGPT Consulting", "label": "ChatGPT Consulting"},
  {"value": "Cloud Consulting", "label": "Cloud Consulting"},
  {"value": "CMS", "label": "CMS"},
  {"value": "Cyber Security", "label": "Cyber Security"},
  {"value": "Data Analytics", "label": "Data Analytics"},
  {"value": "E-commerce", "label": "E-commerce"},
  {"value": "eComm Strategy", "label": "eComm Strategy"},
  {"value": "ERP", "label": "ERP"},
  {"value": "Game Development", "label": "Game Development"},
  {"value": "Innovation Consulting", "label": "Innovation Consulting"},
  {"value": "IT Security", "label": "IT Security"},
  {"value": "Machine learning", "label": "Machine learning"},
  {"value": "Mobile App Development(iOS/Android)", "label": "Mobile App Development(iOS/Android)"},
  {"value": "Product Management", "label": "Product Management"},
  {"value": "Product Strategy", "label": "Product Strategy"},
  {"value": "SaaS Strategy Consulting", "label": "SaaS Strategy Consulting"},
  {"value": "Software Development", "label": "Software Development"},
  {"value": "System Integration Service", "label": "System Integration Service"},
  {"value": "UI / UX Design", "label": "UI / UX Design"},
  {"value": "Web + App Dev", "label": "Web + App Dev"},
  {"value": "Web Analytics", "label": "Web Analytics"},
  {"value": "Web Design", "label": "Web Design"},
  {"value": "Web Development", "label": "Web Development"},
  {"value": "Web3 Development", "label": "Web3 Development"},
  {"value": "Website Administration", "label": "Website Administration"},
  {"value": "Wordpress", "label": "Wordpress"},
];

const List<Map<String, String>> marketingExpertiseData = [
  {"value": "Advertising", "label": "Advertising"},
  {"value": "Branding", "label": "Branding"},
  {"value": "Community Management", "label": "Community Management"},
  {"value": "Content Marketing", "label": "Content Marketing"},
  {"value": "Copywriting", "label": "Copywriting"},
  {"value": "Corporate Communication", "label": "Corporate Communication"},
  {"value": "Digital Marketing", "label": "Digital Marketing"},
  {"value": "Email Marketing", "label": "Email Marketing"},
  {"value": "Event", "label": "Event"},
  {"value": "Growth Marketing", "label": "Growth Marketing"},
  {"value": "Influencer Marketing", "label": "Influencer Marketing"},
  {"value": "Market Research", "label": "Market Research"},
  {"value": "Marketing", "label": "Marketing"},
  {"value": "Media", "label": "Media"},
  {"value": "Online Advertising", "label": "Online Advertising"},
  {"value": "Outdoor Advertising", "label": "Outdoor Advertising"},
  {"value": "Performance marketing", "label": "Performance marketing"},
  {"value": "Print", "label": "Print"},
  {"value": "Public Relations (PR)", "label": "Public Relations (PR)"},
  {"value": "SEO", "label": "SEO"},
  {"value": "Social Media", "label": "Social Media"},
];
