const List<Map<String, String>> techExpertiseData = [
  {'label': "Artificial Intelligence", 'value': "Artificial Intelligence"},
  {'label': "Data Analytics", 'value': "Data Analytics"},
  {'label': "Ecommerce", 'value': "Ecommerce"},
  {'label': "eComm Strategy", 'value': "eComm Strategy"},
  {'label': "Game Development", 'value': "Game Development"},
  {'label': "Innovation Consulting", 'value': "Innovation Consulting"},
  {'label': "Mobile App Development", 'value': "Mobile App Development"},
  {'label': "Product Management", 'value': "Product Management"},
  {'label': "Product Strategy", 'value': "Product Strategy"},
  {'label': "SEO", 'value': "SEO"},
  {'label': "Software Development", 'value': "Software Development"},
  {'label': "UI/UX Design", 'value': "UI/UX Design"},
  {'label': "Web Analytics", 'value': "Web Analytics"},
  {'label': "Web Design", 'value': "Web Design"},
  {'label': "Web Development", 'value': "Web Development"},
];

const List<Map<String, String>> marketingExpertiseData = [
  {'label': "Advertising", 'value': "Advertising"},
  {'label': "Branding", 'value': "Branding"},
  {'label': "Community Management", 'value': "Community Management"},
  {'label': "Content Marketing", 'value': "Content Marketing"},
  {'label': "Copywriting", 'value': "Copywriting"},
  {'label': "Corporate Communication", 'value': "Corporate Communication"},
  {'label': "Digital Marketing", 'value': "Digital Marketing"},
  {'label': "Email Marketing", 'value': "Email Marketing"},
  {'label': "Event", 'value': "Event"},
  {'label': "Growth Marketing", 'value': "Growth Marketing"},
  {'label': "Influencer Marketing", 'value': "Influencer Marketing"},
  {'label': "Market Research", 'value': "Market Research"},
  {'label': "Marketing", 'value': "Performance Analysis"},
  {'label': "Media", 'value': "Media"},
  {'label': "Online Advertising", 'value': "Online Advertising"},
  {'label': "Outdoor Advertising", 'value': "Outdoor Advertising"},
  {'label': "Performance Marketing", 'value': "Performance Marketing"},
  {'label': "Print", 'value': "Print"},
  {'label': "Public Relations(PR)", 'value': "Public Relations(PR)"},
  {'label': "Social Media", 'value': "Social Media"},
];
