const List<Map<String, String>> postListData = [
  {'label': "CEO (Chief Executive Officer)", 'value': "CEO (Chief Executive Officer)"},
  {'label': "Managing Director", 'value': "Managing Director"},
  {'label': "General Manager", 'value': "General Manager"},
  {'label': "Operations Manager", 'value': "Operations Manager"},
  {'label': "Department Head", 'value': "Department Head"},
  {'label': "Team Lead", 'value': "Team Lead"},
  {'label': "Project Manager", 'value': "Project Manager"},
  {'label': "Program Manager", 'value': "Program Manager"},
  {'label': "Director of [Department/Function]", 'value': "Director of [Department/Function]"},
  {'label': "Vice President of [Department/Function]", 'value': "Vice President of [Department/Function]"},
  {'label': "Sales Representative", 'value': "Sales Representative"},
  {'label': "Account Manager", 'value': "Account Manager"},
  {'label': "Business Development Manager", 'value': "Business Development Manager"},
  {'label': "Marketing Manager", 'value': "Marketing Manager"},
  {'label': "Sales Manager", 'value': "Sales Manager"},
  {'label': "Brand Manager", 'value': "Brand Manager"},
  {'label': "Product Manager", 'value': "Product Manager"},
  {'label': "Customer Success Manager", 'value': "Customer Success Manager"},
  {'label': "Sales Engineer", 'value': "Sales Engineer"},
  {'label': "Marketing Coordinator", 'value': "Marketing Coordinator"},
  {'label': "Software Engineer", 'value': "Software Engineer"},
  {'label': "Data Scientist", 'value': "Data Scientist"},
  {'label': "IT Project Manager", 'value': "IT Project Manager"},
  {'label': "Network Administrator", 'value': "Network Administrator"},
  {'label': "Cyber Security Specialist", 'value': "Cyber Security Specialist"},
  {'label': "Database Administrator", 'value': "Database Administrator"},
  {'label': "Web Developer", 'value': "Web Developer"},
  {'label': "UX/UI Designer", 'value': "UX/UI Designer"},
  {'label': "DevOps Engineer", 'value': "DevOps Engineer"},
  {'label': "Cloud Architect", 'value': "Cloud Architect"},
  {'label': "Financial Analyst", 'value': "Financial Analyst"},
  {'label': "Accountant", 'value': "Accountant"},
  {'label': "Financial Manager", 'value': "Financial Manager"},
  {'label': "Investment Banker", 'value': "Investment Banker"},
  {'label': "Portfolio Manager", 'value': "Portfolio Manager"},
  {'label': "Risk Management Specialist", 'value': "Risk Management Specialist"},
  {'label': "Auditor", 'value': "Auditor"},
  {'label': "Tax Consultant", 'value': "Tax Consultant"},
  {'label': "Financial Planner", 'value': "Financial Planner"},
  {'label': "Bookkeeper", 'value': "Bookkeeper"},
  {'label': "HR Generalist", 'value': "HR Generalist"},
  {'label': "Recruiter", 'value': "Recruiter"},
  {'label': "Talent Acquisition Manager", 'value': "Talent Acquisition Manager"},
  {'label': "HR Manager", 'value': "HR Manager"},
  {'label': "Benefits Administrator", 'value': "Benefits Administrator"},
  {'label': "Compensation Analyst", 'value': "Compensation Analyst"},
  {'label': "Training and Development Manager", 'value': "Training and Development Manager"},
  {'label': "Employee Engagement Specialist", 'value': "Employee Engagement Specialist"},
  {'label': "Labor Relations Specialist", 'value': "Labor Relations Specialist"},
  {'label': "Diversity and Inclusion Manager", 'value': "Diversity and Inclusion Manager"},
  {'label': "Doctor/Physician", 'value': "Doctor/Physician"},
  {'label': "Nurse Practitioner", 'value': "Nurse Practitioner"},
  {'label': "Registered Nurse", 'value': "Registered Nurse"},
  {'label': "Medical Researcher", 'value': "Medical Researcher"},
  {'label': "Healthcare Administrator", 'value': "Healthcare Administrator"},
  {'label': "Clinical Trial Manager", 'value': "Clinical Trial Manager"},
  {'label': "Medical Writer", 'value': "Medical Writer"},
  {'label': "Health Educator", 'value': "Health Educator"},
  {'label': "Medical Sales Representative", 'value': "Medical Sales Representative"},
  {'label': "Healthcare Consultant", 'value': "Healthcare Consultant"},
  {'label': "Teacher", 'value': "Teacher"},
  {'label': "Professor", 'value': "Professor"},
  {'label': "Education Administrator", 'value': "Education Administrator"},
  {'label': "Curriculum Developer", 'value': "Curriculum Developer"},
  {'label': "Instructional Designer", 'value': "Instructional Designer"},
  {'label': "Academic Advisor", 'value': "Academic Advisor"},
  {'label': "Education Researcher", 'value': "Education Researcher"},
  {'label': "School Counselor", 'value': "School Counselor"},
  {'label': "University Administrator", 'value': "University Administrator"},
  {'label': "Education Policy Analyst", 'value': "Education Policy Analyst"},
  {'label': "Graphic Designer", 'value': "Graphic Designer"},
  {'label': "Art Director", 'value': "Art Director"},
  {'label': "Creative Director", 'value': "Creative Director"},
  {'label': "Copywriter", 'value': "Copywriter"},
  {'label': "Photographer", 'value': "Photographer"},
  {'label': "Videographer", 'value': "Videographer"},
  {'label': "Editor", 'value': "Editor"},
  {'label': "Writer", 'value': "Writer"},
  {'label': "Illustrator", 'value': "Illustrator"},
  {'label': "Animator", 'value': "Animator"},
  {'label': "Electrician", 'value': "Electrician"},
  {'label': "Plumber", 'value': "Plumber"},
  {'label': "Carpenter", 'value': "Carpenter"},
  {'label': "HVAC Technician", 'value': "HVAC Technician"},
  {'label': "Automotive Technician", 'value': "Automotive Technician"},
  {'label': "Welder", 'value': "Welder"},
  {'label': "Machinist", 'value': "Machinist"},
  {'label': "Locksmith", 'value': "Locksmith"},
  {'label': "Telecommunications Technician", 'value': "Telecommunications Technician"},
  {'label': "Construction Manager", 'value': "Construction Manager"},
  {'label': "Program Manager", 'value': "Program Manager"},
  {'label': "Development Director", 'value': "Development Director"},
  {'label': "Grant Writer", 'value': "Grant Writer"},
  {'label': "Community Organizer", 'value': "Community Organizer"},
  {'label': "Social Worker", 'value': "Social Worker"},
  {'label': "Non-Profit Manager", 'value': "Non-Profit Manager"},
  {'label': "Fundraising Manager", 'value': "Fundraising Manager"},
  {'label': "Advocacy Specialist", 'value': "Advocacy Specialist"},
  {'label': "Public Policy Analyst", 'value': "Public Policy Analyst"},
  {'label': "Environmental Specialist", 'value': "Environmental Specialist"}
];
