const List<Map<String, String>> serviceData = [
  {'label': "Website Development", 'value': "Website Development"},
  {'label': "Website Maintenance", 'value': "Website Maintenance"},
  {'label': "WordPress", 'value': "WordPress"},
  {'label': "Shopify", 'value': "Shopify"},
  {'label': "Custom Websites", 'value': "Custom Websites"},
  {'label': "Web Applications", 'value': "Web Applications"},
  {'label': "Desktop Applications", 'value': "Desktop Applications"},
  {'label': "Game Development", 'value': "Game Development"},
  {'label': "Chatbot Development", 'value': "Chatbot Development"},
  {'label': "Browser Extensions", 'value': "Browser Extensions"},
  {'label': "Software Development", 'value': "Software Development"},
  {'label': "AI Development", 'value': "AI Development"},
  {'label': "APIs & Integrations", 'value': "APIs & Integrations"},
  {'label': "Scripting", 'value': "Scripting"},
  {'label': "Plugins Development", 'value': "Plugins Development"},
  {'label': "Mobile App Development", 'value': "Mobile App Development"},
  {'label': "Cross-platform Apps", 'value': "Cross-platform Apps"},
  {'label': "Android App Development", 'value': "Android App Development"},
  {'label': "IOS App Development", 'value': "IOS App Development"},
  {'label': "Mobile App Maintenance", 'value': "Mobile App Maintenance"},
  {'label': "Wix", 'value': "Wix"},
  {'label': "Webflow", 'value': "Webflow"},
  {'label': "GoDaddy", 'value': "GoDaddy"},
  {'label': "Squarespace", 'value': "Squarespace"},
  {'label': "WooCommerce", 'value': "WooCommerce"},
  {'label': "Support & IT", 'value': "Support & IT"},
  {'label': "Cloud Computing", 'value': "Cloud Computing"},
  {'label': "DevOps Engineering", 'value': "DevOps Engineering"},
  {'label': "Cybersecurity", 'value': "Cybersecurity"},
  {'label': "Development for Streamers", 'value': "Development for Streamers"},
  {'label': "Convert files", 'value': "Convert files"},
  {'label': "Blockchain Development & Solutions", 'value': "Blockchain Development & Solutions"},
  {'label': "Coin Design & Tokenization", 'value': "Coin Design & Tokenization"},
  {'label': "Blockchain Security & Auditing", 'value': "Blockchain Security & Auditing"},
  {'label': "Exchange Platforms", 'value': "Exchange Platforms"},
  {'label': "Website Design", 'value': "Website Design"},
  {'label': "App Design", 'value': "App Design"},
  {'label': "UX Design", 'value': "UX Design"},
  {'label': "Landing Page Design", 'value': "Landing Page Design"},
  {'label': "Icon Design", 'value': "Icon Design"},
  {'label': "Search Engine Optimization (SEO)", 'value': "Search Engine Optimization (SEO)"},
  {'label': "Search Engine Marketing (SEM)", 'value': "Search Engine Marketing (SEM)"},
  {'label': "Local SEO", 'value': "Local SEO"},
  {'label': "E-Commerce SEO", 'value': "E-Commerce SEO"},
  {'label': "Video SEO", 'value': "Video SEO"},
  {'label': "Social Media Marketing", 'value': "Social Media Marketing"},
  {'label': "Paid Social Media", 'value': "Paid Social Media"},
  {'label': "Social Commerce ", 'value': "Social Commerce "},
  {'label': "Influencer Marketing", 'value': "Influencer Marketing"},
  {'label': "Community Management", 'value': "Community Management"},
  {'label': "Video Marketing", 'value': "Video Marketing"},
  {'label': "E-Commerce Marketing", 'value': "E-Commerce Marketing"},
  {'label': "Email Marketing", 'value': "Email Marketing"},
  {'label': "Email Automations", 'value': "Email Automations"},
  {'label': "Guest Posting", 'value': "Guest Posting"},
  {'label': "Affiliate Marketing", 'value': "Affiliate Marketing"},
  {'label': "Display Advertising", 'value': "Display Advertising"},
  {'label': "Public Relations", 'value': "Public Relations"},
  {'label': "Text Message Marketing", 'value': "Text Message Marketing"},
  {'label': "Marketing Strategy", 'value': "Marketing Strategy"},
  {'label': "Marketing Concepts & Ideation", 'value': "Marketing Concepts & Ideation"},
  {'label': "Marketing Advice", 'value': "Marketing Advice"},
  {'label': "Web Analytics", 'value': "Web Analytics"},
  {'label': "Conversion Rate Optimization (CRO)", 'value': "Conversion Rate Optimization (CRO)"},
  {'label': "Music Promotion", 'value': "Music Promotion"},
  {'label': "Podcast Marketing", 'value': "Podcast Marketing"},
  {'label': "Book & eBook Marketing", 'value': "Book & eBook Marketing"},
  {'label': "International Public Relations", 'value': "International Public Relations"},
  {'label': "Investor Relations", 'value': "Investor Relations"},
  {'label': "Investors Outreach", 'value': "Investors Outreach"},
  {'label': "Online PR", 'value': "Online PR"},
  {'label': "Public Affairs", 'value': "Public Affairs"},
  {'label': "Public Relations (PR)", 'value': "Public Relations (PR)"},
  {'label': "Billboard Design", 'value': "Billboard Design"},
  {'label': "Field Marketing", 'value': "Field Marketing"},
  {'label': "Outdoor Advertising", 'value': "Outdoor Advertising"},
  {'label': "Out Of Home Advertising", 'value': "Out Of Home Advertising"},
  {'label': "Street Marketing", 'value': "Street Marketing"},
  {'label': "Media", 'value': "Media"},
  {'label': "Media Buying", 'value': "Media Buying"},
  {'label': "Print Media Buying", 'value': "Print Media Buying"},
  {'label': "Radio Media Buying", 'value': "Radio Media Buying"},
  {'label': "TV Media Buying", 'value': "TV Media Buying"},
  {'label': "360° Marketing", 'value': "360° Marketing"},
  {'label': "AI Marketing", 'value': "AI Marketing"},
  {'label': "Ambient Marketing", 'value': "Ambient Marketing"},
  {'label': "Attribution Marketing", 'value': "Attribution Marketing"},
  {'label': "B2B Marketing", 'value': "B2B Marketing"},
  {'label': "B2C Marketing", 'value': "B2C Marketing"},
  {'label': "Blockchain Marketing", 'value': "Blockchain Marketing"},
  {'label': "Communication Strategy", 'value': "Communication Strategy"},
  {'label': "Competitive Analysis", 'value': "Competitive Analysis"},
  {'label': "Consumer Marketing", 'value': "Consumer Marketing"},
  {'label': "Creative Communication", 'value': "Creative Communication"},
  {'label': "Crisis Communication", 'value': "Crisis Communication"},
  {'label': "Cross-Platform Marketing", 'value': "Cross-Platform Marketing"},
  {'label': "Cultural Communication", 'value': "Cultural Communication"},
  {'label': "Data Driven Marketing", 'value': "Data Driven Marketing"},
  {'label': "Digital Communication", 'value': "Digital Communication"},
  {'label': "Direct Marketing", 'value': "Direct Marketing"},
  {'label': "Editorial Communication", 'value': "Editorial Communication"},
  {'label': "Endorsement Marketing", 'value': "Endorsement Marketing"},
  {'label': "Environmental Communication", 'value': "Environmental Communication"},
  {'label': "Experiential Marketing", 'value': "Experiential Marketing"},
  {'label': "Experimental Marketing", 'value': "Experimental Marketing"},
  {'label': "Fair Trade Marketing", 'value': "Fair Trade Marketing"},
  {'label': "Global Communication", 'value': "Global Communication"},
  {'label': "Integrated Marketing", 'value': "Integrated Marketing"},
  {'label': "Interactive Marketing", 'value': "Interactive Marketing"},
  {'label': "International Marketing", 'value': "International Marketing"},
  {'label': "Local Marketing", 'value': "Local Marketing"},
  {'label': "Luxury Marketing", 'value': "Luxury Marketing"},
  {'label': 'Marketing', 'value': 'Marketing'},
  {'label': 'Marketing Analytics', 'value': 'Marketing Analytics'},
  {'label': 'Marketing Automation', 'value': 'Marketing Automation'},
  {'label': 'Marketing Benchmark', 'value': 'Marketing Benchmark'},
  {'label': 'Marketing Communication', 'value': 'Marketing Communication'},
  {'label': 'Marketing Consulting', 'value': 'Marketing Consulting'},
  {'label': 'Marketing Research', 'value': 'Marketing Research'},
  {'label': 'Marketing Services', 'value': 'Marketing Services'},
  {'label': 'Marketing Strategy', 'value': 'Marketing Strategy'},
  {'label': 'Mobile Marketing', 'value': 'Mobile Marketing'},
  {'label': 'Multichannel Marketing', 'value': 'Multichannel Marketing'},
  {'label': "Neuromarketing", 'value': "Neuromarketing"},
  {'label': "Offline marketing", 'value': "Offline marketing"},
  {'label': "Omnichannel Marketing", 'value': "Omnichannel Marketing"},
  {'label': "Outbound Marketing", 'value': "Outbound Marketing"},
  {'label': "Postcard Marketing", 'value': "Postcard Marketing"},
  {'label': "Print Communication", 'value': "Print Communication"},
  {'label': "Proximity Marketing", 'value': "Proximity Marketing"},
  {'label': "Recruitment Marketing", 'value': "Recruitment Marketing"},
  {'label': "Relationship Marketing", 'value': "Relationship Marketing"},
  {'label': "Reputation Management", 'value': "Reputation Management"},
  {'label': "Retail Marketing", 'value': "Retail Marketing"},
  {'label': "Shopper Marketing", 'value': "Shopper Marketing"},
  {'label': "Social Impact", 'value': "Social Impact"},
  {'label': "Sports Marketing", 'value': "Sports Marketing"},
  {'label': "Sustainable Marketing", 'value': "Sustainable Marketing"},
  {'label': "Telemarketing", 'value': "Telemarketing"},
  {'label': "Territorial Marketing", 'value': "Territorial Marketing"},
  {'label': "Trade Marketing", 'value': "Trade Marketing"},
  {'label': "Travel Marketing", 'value': "Travel Marketing"},
  {'label': "Viral Marketing", 'value': "Viral Marketing"},
  {'label': "Visual Communication", 'value': "Visual Communication"},
  {'label': "B2B Influencer Marketing", 'value': "B2B Influencer Marketing"},
  {'label': "Influencer Marketing", 'value': "Influencer Marketing"},
  {'label': "Instagram Influencer", 'value': "Instagram Influencer"},
  {'label': "360º Advertising", 'value': "360º Advertising"},
  {'label': "Advertising", 'value': "Advertising"},
  {'label': "Advertising Campaign", 'value': "Advertising Campaign"},
  {'label': "Advertising Production", 'value': "Advertising Production"},
  {'label': "Banner Advertising", 'value': "Banner Advertising"},
  {'label': "Billboard Advertising", 'value': "Billboard Advertising"},
  {'label': "Brand Advertising", 'value': "Brand Advertising"},
  {'label': "Corporate Advertising", 'value': "Corporate Advertising"},
  {'label': "Creative", 'value': "Creative"},
  {'label': "Full-Service", 'value': "Full-Service"},
  {'label': "Graphic Advertising", 'value': "Graphic Advertising"},
  {'label': "Guerilla Advertising", 'value': "Guerilla Advertising"},
  {'label': "Interactive Advertising", 'value': "Interactive Advertising"},
  {'label': "Luxury Advertising", 'value': "Luxury Advertising"},
  {'label': "Multicultural Advertising", 'value': "Multicultural Advertising"},
  {'label': "OTT Advertising", 'value': "OTT Advertising"},
  {'label': "Point of Sale (POS) Display", 'value': "Point of Sale (POS) Display"},
  {'label': "Radio Advertising", 'value': "Radio Advertising"},
  {'label': "TV Advertising", 'value': "TV Advertising"},
  {'label': "Affiliate Advertising", 'value': "Affiliate Advertising"},
  {'label': "Affiliate Marketing", 'value': "Affiliate Marketing"},
  {'label': "Amazon Marketing", 'value': "Amazon Marketing"},
  {'label': "Amazon PPC", 'value': "Amazon PPC"},
  {'label': "Baidu Advertising", 'value': "Baidu Advertising"},
  {'label': "Baidu PPC", 'value': "Baidu PPC"},
  {'label': "Bing Ads", 'value': "Bing Ads"},
  {'label': "Connected TV Advertising (CTV)", 'value': "Connected TV Advertising (CTV)"},
  {'label': "Digital Advertising", 'value': "Digital Advertising"},
  {'label': "Display Advertising", 'value': "Display Advertising"},
  {'label': "Facebook Ads", 'value': "Facebook Ads"},
  {'label': "Google Ads", 'value': "Google Ads"},
  {'label': "Instagram Advertising", 'value': "Instagram Advertising"},
  {'label': "LinkedIn Ads", 'value': "LinkedIn Ads"},
  {'label': "Mobile Advertising", 'value': "Mobile Advertising"},
  {'label': "Native Advertising", 'value': "Native Advertising"},
  {'label': "Online Advertising", 'value': "Online Advertising"},
  {'label': "Paid Media", 'value': "Paid Media"},
  {'label': "Pay-Per-Click", 'value': "Pay-Per-Click"},
  {'label': "Performance Marketing", 'value': "Performance Marketing"},
  {'label': "Programmatic Advertising", 'value': "Programmatic Advertising"},
  {'label': "Retargeting", 'value': "Retargeting"},
  {'label': "ROI Optimization", 'value': "ROI Optimization"},
  {'label': "SEA", 'value': "SEA"},
  {'label': "TikTok Advertising", 'value': "TikTok Advertising"},
  {'label': "Twitter Advertising", 'value': "Twitter Advertising"},
  {'label': "Xing Ads", 'value': "Xing Ads"},
  {'label': "Yahoo Advertising", 'value': "Yahoo Advertising"},
  {'label': "YouTube Advertising", 'value': "YouTube Advertising"}
];
