// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19dOC41i7r9LQGo3xE0ksvYSBwqMzCPo',
    appId: '1:446689292363:ios:1aaec006a681d6fb85ddce',
    messagingSenderId: '446689292363',
    projectId: 'briefsea',
    storageBucket: 'briefsea.appspot.com',
    iosClientId: '446689292363-t54ihuipku9s4o9djs90cpjmardfnhva.apps.googleusercontent.com',
    iosBundleId: 'com.briefsea.briefsea',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASu24AdWePkiWGWf69Qwe1XsD31_06GDU',
    appId: '1:446689292363:android:6d097ae98c167e3f85ddce',
    messagingSenderId: '446689292363',
    projectId: 'briefsea',
    storageBucket: 'briefsea.appspot.com',
  );

}